---
- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Upload via TFTP
      aoscx_command:
        commands:
        - command: 'copy tftp://10.0.9.87/TL_10_08_0001CN.swi secondary vrf mgmt'
          prompt:
            - '.*Continue.*'
          answer:
            - y

    - name: Show images
      aoscx_command:
        commands: ["show image"]

- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Upload via SFTP
      aoscx_command:
        commands:
          - command: "copy sftp://chiapuzi@10.0.9.87/TL_10_07_0030O.swi primary vrf mgmt"
            check_all: True
            prompt:
              - '.*\(y\/n\)\?.*'
              - '.*password:.*'
            answer:
              - 'y'
              - 'password'

    - name: Show images
      aoscx_command:
        commands: ["show image"]

- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: False
  vars:
    ansible_connection: network_cli        
  tasks:
    - name: Optional - Accept authenticity Upload via SCP
      aoscx_command:
        commands:
          - command: "copy scp://administrator@10.80.2.153/config.txt running-config vrf mgmt"
            check_all: True
            prompt:
              - '.*\(yes\/no.*\)\?.*'
            answer:
              - 'yes'
      ignore_errors: True
      # If fingerprint prompt does not come up then this will fail which is okay

    - name: Copy config via SCP
      aoscx_command:
        commands:
          - command: "copy scp://administrator@10.80.2.153/config.txt running-config vrf mgmt"
            prompt:
              - '.*password:.*'
            answer:
              - 'password'          
